Workflow updates (#485)
* l10n-pull now creates draft PRs

* show more errors in the UI

* tell GitHub about generated files

* ci: fix pull_request trigger

* ci: fix wrong cwd in client_game_test

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -2,6 +2,7 @@ name: Build
 
 on:
   pull_request:
+    types: [opened, ready_for_review, synchronize]
   push:
     branches: [main]
   workflow_dispatch:
@@ -47,10 +48,12 @@ jobs:
           reports: reference/**/build/reports/checkstyle/*.xml
       # require clean working directory
       - run: |
-          if [ -n "$(git status --porcelain)" ]; then
-            git status
-            exit 1
-          fi
+          files="$(git ls-files --modified --others --exclude-standard -z)"
+          [[ -z "${files}" ]] && exit 0
+          while IFS= read -r -d '' f; do
+            echo "::error file=${f},title=Datagen::Regenerate this file with 'cd reference && ./gradlew runDatagen'"
+          done <<<"${files}"
+          exit 1
 
   # :::automatic-testing:game-test:3
   client_game_test:
@@ -64,12 +67,13 @@ jobs:
       - run: ./gradlew runProductionClientGameTest
         # :::automatic-testing:game-test:3
         working-directory: ./reference
-      # :::automatic-testing:game-test:3
+        # :::automatic-testing:game-test:3
       - if: always()
         uses: actions/upload-artifact@v4
         with:
           path: build/run/clientGameTest/screenshots
-  # :::automatic-testing:game-test:3
+        # :::automatic-testing:game-test:3
+        working-directory: ./reference
 
   deploy:
     runs-on: ubuntu-24.04
diff --git a/.github/workflows/l10n-pull.yaml b/.github/workflows/l10n-pull.yaml
--- a/.github/workflows/l10n-pull.yaml
+++ b/.github/workflows/l10n-pull.yaml
@@ -29,7 +29,9 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
       - if: startsWith(github.ref_name, 'l10n/')
-        run: exit 1
+        run: |
+          echo "::error title=Wrong Branch::This workflow must not be triggered from the l10n/* branch"
+          exit 1
       - uses: actions/checkout@v4
       - uses: crowdin/github-action@60debf382ee245b21794321190ad0501db89d8c1
         with:
@@ -68,7 +70,6 @@ jobs:
           body: ""
           commit-message: ${{ steps.message.outputs.message }}
           branch: l10n/${{ github.ref_name }}
-          author: Fabric Bot <159731069+FabricMCBot@users.noreply.github.com>
-          committer: Fabric Bot <159731069+FabricMCBot@users.noreply.github.com>
           labels: i18n-l10n
+          draft: always-true
           maintainer-can-modify: false
