show more errors in the UI

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -48,10 +48,12 @@ jobs:
           reports: reference/**/build/reports/checkstyle/*.xml
       # require clean working directory
       - run: |
-          if [ -n "$(git status --porcelain)" ]; then
-            git status
-            exit 1
-          fi
+          files="$(git ls-files --modified --others --exclude-standard -z)"
+          [[ -z "${files}" ]] && exit 0
+          while IFS= read -r -d '' f; do
+            echo "::error file=${f},title=Datagen::Regenerate this file with 'cd reference && ./gradlew runDatagen'"
+          done <<<"${files}"
+          exit 1
 
   # :::automatic-testing:game-test:3
   client_game_test:
diff --git a/.github/workflows/format.yaml b/.github/workflows/format.yaml
--- a/.github/workflows/format.yaml
+++ b/.github/workflows/format.yaml
@@ -43,4 +43,11 @@ jobs:
         with:
           node-version-file: .nvmrc
       - run: npm ci
-      - run: npx prettier --list-different .
+      - run: npx prettier --write .
+      - run: |
+          files="$(git ls-files --modified --others --exclude-standard -z)"
+          [[ -z "${files}" ]] && exit 0
+          while IFS= read -r -d '' f; do
+            echo "::error file=${f},title=Prettier::Format this file with 'npx prettier --write \"${f}\"'"
+          done <<<"${files}"
+          exit 1
diff --git a/.github/workflows/l10n-pull.yaml b/.github/workflows/l10n-pull.yaml
--- a/.github/workflows/l10n-pull.yaml
+++ b/.github/workflows/l10n-pull.yaml
@@ -29,7 +29,9 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
       - if: startsWith(github.ref_name, 'l10n/')
-        run: exit 1
+        run: |
+          echo "::error title=Wrong Branch::This workflow must not be triggered from the l10n/* branch"
+          exit 1
       - uses: actions/checkout@v4
       - uses: crowdin/github-action@60debf382ee245b21794321190ad0501db89d8c1
         with:
